### ISSUE TITLE
Validar/Ajustar ambientes de prueba y produccion

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/contabilidad_cliente#116]
Hacer una (o más) rama(s) `feature/...` para lo siguiente:

- [x] Limpiar variables de entorno ([referencia](https://github.com/udistrital/central_cuentas_cliente/issues/130))
- [x] Actualizar pipelines ([referencia 1](https://github.com/udistrital/tesoreria_cliente/pull/106/commits/137eac13125d79d44a91aae4b82d87ac4c4de463) + [referencia 2](https://github.com/udistrital/tesoreria_cliente/pull/106/commits/e07dae71546fd985985916cec16bc74c6fd5b2e3))
- [x] Ajustar stylelint y validaciones antes del push ([referencia](https://github.com/udistrital/tesoreria_cliente/pull/106/commits/17d3f3447ea7789e29ae40daacb426d7e09be032))
- [x] Corregir "errores" (por malas practicas de codigo) despues de lo anterior ([referencia](https://github.com/udistrital/tesoreria_cliente/issues/107))

Edit 10/08/21 by @AlexFBP:
- [x] Validar si udistrital/cuentas_contables_crud#48 era necesario, y según se identifique, comentarlo en udistrital/cuentas_contables_crud#53

Solo cuando esté(n) fusionada(s todas) la(s) rama(s) relacionada(s) a lo anterior:
- [x] hacer la rama `release/0.1.0`, debe incluir el package.json y README.md actualizados para la versión indicada (y el package-lock.json, que se actualiza después de actualizar el package.json y correr el `npm i`)
- [x] Abrir 2 PRs, uno a master y otro de vuelta a Develop ([lineamiento de ramas](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md))
- [x] (Si aplica) Ajustar para que el build `release/...` funcione
- [x] (Si aplica, y después de aprobado y aplicado el PR a `master`)Ajustar para que el build master funcione, mediante rama `hotfix/...`
- [x] (En caso de presentarse algo similar a [esto](https://github.com/udistrital/tesoreria_cliente/issues/107) o a [esto](https://github.com/udistrital/central_cuentas_cliente/issues/133)) Ajustar el menú en producción / `master`

**Comment by Jeisson005** [comment]
Para limpiar variables de entorno se realiza lo siguiente:
- [ ] Sincronizar y Revisar las variables de entorno, de develop (src/app/environment.ts) a los demás entornos (environment.*.ts).
- [ ] Reducir los archivos en src/environments/
- [ ] Actualizar el job para develop y release
- [ ] En src/environments/, agregar un archivo .gitignore para el environment.ts y para el environment.dev.ts
- [ ] En src/environments/, agregar un README.md

**Comment by Jeisson005** [comment]
Para la actualización de los pipelines:
- [ ] Se ajusta el archivo .drone.yml agregando, agregando la rama hotfix y validando nombres y procedimientos de las demás
- [ ] Se quitan los comentarios del procedimientos de pruebas_unitarias

**Comment by Jeisson005** [comment]
Para los ajustes de stylelint y validaciones antes del push:

- [ ] Cambio de _npm run lint:**ci**_
- [ ] Adición del archivo _.stylelintrc.json_
- [ ] Actualización del archivo _package.json_ con el nombre y url del proyecto
- [ ] Ejecución de _npm audit fix_ para corrección de dependencias, se actualiza a su vez archivo _package.json_ y _package-lock.json_
- [ ] Se ejecuta _ng lint_, _npm run lint:ci_ y se solucionan los errores mostrados

**Comment by Jeisson005** [comment]
Para la correción de errores por malas prácticas de código:
- [x] Se ejecuta _ng lint_, _npm run lint:ci_ y se solucionan los errores mostrados
- [ ]

**Comment by AlexFBP** [comment]
Respecto a estas advertencias:

> ```
> Linting "ngx-admin-demo"...
> no-use-before-declare is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
> typeof-compare is deprecated. Starting from TypeScript 2.2 the compiler includes this check which makes this rule redundant.
> no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
> All files pass linting.
> ```

Intentar ajustar en no más de 2h.
En cualquier caso:
- retomar este Issue: proceder con la rama release/0.1.0
- Para el último ítem, dejar en producción cargados todos los menús, pero únicamente habilitados los que se sepa que Contabilidad (usuario) haya aceptado/recibido
